#Hugo configuration
title = "Damian Stage wedrdsf"
baseURL = "https:\/\/werdsf.sxfcd.dg"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"

[params]
loginId = "1758823"
subfolder = ""
